//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string maNV { get; set; }
        public string hoTenNV { get; set; }
        public string GioiTinh { get; set; }
        public string hinh { get; set; }
        public string matkhau { get; set; }
        public string vaitro { get; set; }
    }
}
