//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps18264_ASM_C3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string ID { get; set; }
        public string MASV { get; set; }
        public Nullable<int> TiengAnh { get; set; }
        public Nullable<int> TinHoc { get; set; }
        public Nullable<int> GDTC { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
