//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps18264_ASM_C3
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_login
    {
        public string username { get; set; }
        public string passwork { get; set; }
        public string roles { get; set; }
    }
}
